route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'lenhhoxung98s@gmail.com'
        auth_password: "admin1998"
        from: 'lenhhoxung98s@gmail.com'
        to: 'levancao198@gmail.com'