version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:rw
      - ./targets.yml:/etc/prometheus/targets.yml:rw
      - ./rules:/etc/prometheus/rules:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      over9:

  grafana:
    image: grafana/grafana
    hostname: grafana
    user: root
    volumes:
      - ./grafana_data:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3001:3000"
    networks:
      over9:
  
    alertmanager:
      image: prom/alertmanager:v0.23.0
      restart: unless-stopped
      hostname: alertmanager
      ports:
        - "9093:9093"
      volumes:
        - ./alertmanager:/config
        - ./alertmanager-data:/data
      command: --config.file=/config/alertmanager.yml --log.level=debug

networks:
  over9:
    external: true
    # attachable: true
